[package]
name = "own"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
cargo-watch = "8.5.3"
serde = "1.0.226"
serde_json = "1.0.145"
diesel = { version = "2.3.2", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15.0"
